name: "Test Build"

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-linux-arm:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
         submodules: recursive

    - name: List directory contents
      run: pwd; ls -la

    - name: start xvfb
      run:
        Xvfb :0 &

    - name: initialize the X11 DISPLAY variable
      run:
        export DISPLAY=:0

    - name: After checkout, list directory contents
      run: pwd; ls -la

    - name: Install libraries
      run: |
          sudo apt update
          sudo apt install libgtk2.0-0

    - name: Pull a JavaFX JDK
      run: wget https://cdn.azul.com/zulu/bin/zulu25.36.15-ca-fx-jdk25.0.4-linux_aarch64.tar.gz

    - name: Set Java
      uses: actions/setup-java@v1
      with:
        java-version: 25
        jdkFile: ./zulu25.36.15-ca-fx-jdk25.0.4-linux_aarch64.tar.gz

    - name: Test with Gradle
      run: xvfb-run -s '-screen 0 1024x768x24' ./gradlew test
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
         submodules: recursive

    - name: Pull a JavaFX JDK
      run: curl -O https://cdn.azul.com/zulu/bin/zulu25.36.15-ca-fx-jdk25.0.4-win_x64.zip

    - name: Set Java
      uses: actions/setup-java@v1
      with:
        java-version: 25
        jdkFile: ./zulu25.36.15-ca-fx-jdk25.0.4-win_x64.zip

    - name: Test with Gradle
      run: ./gradlew test
  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
         submodules: recursive
    - name: Install Java and Maven
      run: |
        wget https://cdn.azul.com/zulu/bin/zulu25.36.15-ca-fx-jdk25.0.4-macosx_aarch64.tar.gz
        tar -xzf zulu25.36.15-ca-fx-jdk25.0.4-macosx_aarch64.tar.gz
        echo "JAVA_HOME=$(pwd)/zulu25.36.15-ca-fx-jdk25.0.4-macosx_aarch64" >> $GITHUB_ENV
        echo "PATH=$(pwd)/zulu25.36.15-ca-fx-jdk25.0.4-macosx_aarch64/bin:$PATH" >> $GITHUB_ENV
    - name: Test with Gradle
      run: ./gradlew test
  build-linux-x86:
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:20.04
      options: --user root
    env:
      CC: gcc
      CXX: g++
    steps:
    - run: |
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y \
            unzip \
            curl \
            wget \
            ca-certificates \
            lsb-release \
            gnupg \
            git \
            file \
            xz-utils \
            openjdk-11-jdk \
            gcc \
            g++ \
            make \
            maven \
            libgtk2.0-0 \
            xvfb
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
         submodules: recursive        
        
    - name: List directory contents
      run: pwd; ls -la      
      
    - name: start xvfb
      run:
        Xvfb :0 &

    - name: initialize the X11 DISPLAY variable
      run:
        export DISPLAY=:0

    - name: After checkout, list directory contnts
      run: pwd; ls -la        

    - name: Pull a JavaFX JDK
      run: wget https://cdn.azul.com/zulu/bin/zulu25.36.15-ca-fx-jdk25.0.4-linux_x64.tar.gz

    - name: Set Java
      uses: actions/setup-java@v1
      with:
        java-version: 25
        jdkFile: ./zulu25.36.15-ca-fx-jdk25.0.4-linux_x64.tar.gz

      
    - name: Test with Gradle 
      run: xvfb-run -s '-screen 0 1024x768x24' ./gradlew test     
  
      
